#!/usr/bin/perl

my $dark = [
  { "pos" => 100,  "string" => 'MYNA' },
  { "pos" => 300,  "string" => 'Lorem ipsum dolor sit amet' },
  { "pos" => 500,  "string" => '0 1 2 3 4 5 6 7 8 9' },
  { "pos" => 700,  "string" => '[] {} () <> | / ? ! #' },
  { "pos" => 900,  "string" => '\` \' \" , . ; : ~ ^ _' },
  { "pos" => 1100, "string" => '+ - = ++ -- += -= == !=' },
  { "pos" => 1300, "string" => '\$s @a \%h &f *x =~' },
  { "pos" => 1500, "string" => ':: -> => <$> >>= ^. \%~' },
  { "pos" => 1700, "string" => '$ £ € ¥ ₹ ₽' },
  { "pos" => 1900, "string" => '0 O o | 1 l I | \` \' \" | Z 2' }
];

my $light = [
  { "pos" => 100,  "string" => 'MYNA' },
  { "pos" => 300,  "string" => 'Lorem ipsum dolor sit amet' },
  { "pos" => 500,  "string" => '0 1 2 3 4 5 6 7 8 9' },
  { "pos" => 700,  "string" => '[] {} () <> | / ? ! #' },
  { "pos" => 900,  "string" => '\` \' \" , . ; : ~ ^ _' },
  { "pos" => 1100, "string" => '+ - = ++ -- += -= == !=' },
  { "pos" => 1300, "string" => '\$s @a \%h &f *x =~' },
  { "pos" => 1500, "string" => ':: -> => <$> >>= ^. \%~' },
  { "pos" => 1700, "string" => '$ £ € ¥ ₹ ₽' },
  { "pos" => 1900, "string" => '0 O o | 1 l I | \` \' \" | Z 2' }
];

system(join(' ',
  "magick",
  "-size 2000x2200 xc:black -gravity north -pointsize 128 -font Myna -strokewidth 2",
  (map { "-fill white -stroke white -annotate +0+$_->{pos} \"$_->{string}\"" } $dark->@*),
  quotemeta($ARGV[0])
));

system(join(' ',
  "magick",
  "-size 2000x2200 xc:white -gravity north -pointsize 128 -font Myna -strokewidth 2",
  (map { "-fill black -stroke black -annotate +0+$_->{pos} \"$_->{string}\"" } $light->@*),
  quotemeta($ARGV[1])
));
